services:
  mysql:
    image: 'mysql:8.0.44'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=root_password'
    ports:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: