spring:
  application:
    name: etudiant-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}

jwt:
  secret: Vw0ThEB/ia7oHF6BPE9ARyLGIstx/P07XuUmQKO7I1o=
  expiration: 3600000

logging:
  level:
    org:
      hibernate:
        type: info
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: info
    com:
      openclassrooms:
        etudiant: info

management:
  endpoints:
    web:
      exposure:
        include: '*'